/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingsRouteImport } from './routes/shoppings'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AnalisesRouteImport } from './routes/analises'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingsShoppingIdRouteImport } from './routes/shoppings.$shoppingId'

const ShoppingsRoute = ShoppingsRouteImport.update({
  id: '/shoppings',
  path: '/shoppings',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesRoute = AnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingsShoppingIdRoute = ShoppingsShoppingIdRouteImport.update({
  id: '/$shoppingId',
  path: '/$shoppingId',
  getParentRoute: () => ShoppingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analises': typeof AnalisesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esg': typeof EsgRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRoute
  '/shoppings': typeof ShoppingsRouteWithChildren
  '/shoppings/$shoppingId': typeof ShoppingsShoppingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analises': typeof AnalisesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esg': typeof EsgRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRoute
  '/shoppings': typeof ShoppingsRouteWithChildren
  '/shoppings/$shoppingId': typeof ShoppingsShoppingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analises': typeof AnalisesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/esg': typeof EsgRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRoute
  '/shoppings': typeof ShoppingsRouteWithChildren
  '/shoppings/$shoppingId': typeof ShoppingsShoppingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analises'
    | '/configuracoes'
    | '/esg'
    | '/ranking'
    | '/relatorios'
    | '/shoppings'
    | '/shoppings/$shoppingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analises'
    | '/configuracoes'
    | '/esg'
    | '/ranking'
    | '/relatorios'
    | '/shoppings'
    | '/shoppings/$shoppingId'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analises'
    | '/configuracoes'
    | '/esg'
    | '/ranking'
    | '/relatorios'
    | '/shoppings'
    | '/shoppings/$shoppingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnalisesRoute: typeof AnalisesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EsgRoute: typeof EsgRoute
  RankingRoute: typeof RankingRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ShoppingsRoute: typeof ShoppingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shoppings': {
      id: '/shoppings'
      path: '/shoppings'
      fullPath: '/shoppings'
      preLoaderRoute: typeof ShoppingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises': {
      id: '/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoppings/$shoppingId': {
      id: '/shoppings/$shoppingId'
      path: '/$shoppingId'
      fullPath: '/shoppings/$shoppingId'
      preLoaderRoute: typeof ShoppingsShoppingIdRouteImport
      parentRoute: typeof ShoppingsRoute
    }
  }
}

interface ShoppingsRouteChildren {
  ShoppingsShoppingIdRoute: typeof ShoppingsShoppingIdRoute
}

const ShoppingsRouteChildren: ShoppingsRouteChildren = {
  ShoppingsShoppingIdRoute: ShoppingsShoppingIdRoute,
}

const ShoppingsRouteWithChildren = ShoppingsRoute._addFileChildren(
  ShoppingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnalisesRoute: AnalisesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EsgRoute: EsgRoute,
  RankingRoute: RankingRoute,
  RelatoriosRoute: RelatoriosRoute,
  ShoppingsRoute: ShoppingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
