import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Fan, Gauge, ShieldCheck, Thermometer, Zap } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { liveDashboardService } from "@/services/liveDashboardService";
import type { HistoryPeriod, LiveShoppingSummary, ShoppingApiResponse } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { FilterBar, InternalPage, SectionPanel, StatCard, chartTooltipStyle } from "@/components/InternalPage";
import { formatNumber } from "@/utils/format";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";

export const Route = createFileRoute("/analises")({ head: () => ({ meta: [{ title: "Análises" }] }), component: AnalyticsPage });

type Metric = "kwCag"|"energyKwh"|"trTotal"|"kwTr"|"kwAux"|"temperatureC"|"dataQualityPct";
const METRICS: Record<Metric,{label:string;unit:string;icon:any}> = {
 kwCag:{label:"Potência CAG",unit:"kW",icon:Zap}, energyKwh:{label:"Energia elétrica",unit:"kWh",icon:Activity}, trTotal:{label:"Produção térmica",unit:"TR",icon:Activity}, kwTr:{label:"kW/TR",unit:"kW/TR",icon:Gauge}, kwAux:{label:"Periféricos",unit:"kW",icon:Fan}, temperatureC:{label:"Temperatura externa",unit:"°C",icon:Thermometer}, dataQualityPct:{label:"Qualidade dos dados",unit:"%",icon:ShieldCheck},
};

function AnalyticsPage(){
 const {tick}=useDashboardRuntime(); const [portfolio,setPortfolio]=useState<LiveShoppingSummary[]>([]); const [selected,setSelected]=useState<string[]>([]); const [metric,setMetric]=useState<Metric>("kwCag"); const [period,setPeriod]=useState<HistoryPeriod>("24h"); const [series,setSeries]=useState<ShoppingApiResponse[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;liveDashboardService.getPortfolio().then(p=>{if(!alive)return;setPortfolio(p.shoppings);setSelected(prev=>prev.length?prev:p.shoppings.map(s=>s.code))});return()=>{alive=false}},[tick]);
 useEffect(()=>{if(!selected.length){setSeries([]);setLoading(false);return}let alive=true;setLoading(true);Promise.all(selected.map(code=>liveDashboardService.getShopping(code,period).catch(()=>null))).then(r=>{if(alive)setSeries(r.filter((x):x is ShoppingApiResponse=>!!x))}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[selected,period,tick]);
 const config=METRICS[metric]; const summaryValues=useMemo(()=>series.map(s=>metric==="energyKwh"?s.summary.energyKwh:average(s.history.map(h=>h[metric] as number|null))).filter((v):v is number=>v!==null),[series,metric]); const avg=average(summaryValues); const max=summaryValues.length?Math.max(...summaryValues):null; const min=summaryValues.length?Math.min(...summaryValues):null;
 return <InternalPage><PageHeader eyebrow="Histórico consolidado" title="Análises" subtitle="Cruze potência, energia, produção térmica, kW/TR, periféricos, temperatura externa e qualidade dos dados." icon={BarChart3}/>
 <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard label="Unidades selecionadas" value={selected.length} icon={BarChart3} accent="cyan"/><StatCard label="Média" value={num(avg,3)} unit={config.unit} icon={config.icon} accent="green"/><StatCard label="Máximo" value={num(max,3)} unit={config.unit} icon={Activity} accent="yellow"/><StatCard label="Mínimo" value={num(min,3)} unit={config.unit} icon={Gauge} accent="blue"/></div>
 <FilterBar><label className="flex min-w-[180px] flex-col gap-1 text-[10px] uppercase tracking-[.12em] text-muted-foreground">Métrica<select value={metric} onChange={e=>setMetric(e.target.value as Metric)} className="h-9 rounded-lg border border-border/60 bg-background/55 px-2.5 text-sm normal-case tracking-normal text-foreground">{Object.entries(METRICS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><div className="segmented-control self-end">{(["24h","7d","30d"] as HistoryPeriod[]).map(p=><button type="button" key={p} data-active={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="ml-auto flex flex-wrap items-end gap-2">{portfolio.map(s=><label key={s.code} className="flex items-center gap-1.5 rounded-lg border border-border/55 bg-background/45 px-2.5 py-2 text-xs"><input type="checkbox" checked={selected.includes(s.code)} onChange={()=>setSelected(prev=>prev.includes(s.code)?prev.filter(x=>x!==s.code):[...prev,s.code])}/>{s.code}</label>)}</div></FilterBar>
 <SectionPanel title={`Comparação · ${config.label}`} subtitle={`Período: ${period}`} icon={config.icon}>{loading?<LoadingBlock h={390}/>:series.length===0?<EmptyState title="Sem séries disponíveis"/>:<div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{series.map(s=><div key={s.shopping?.code} className="rounded-xl border border-border/55 bg-muted/10 p-3"><div className="mb-2 flex items-center justify-between"><div><div className="text-sm font-semibold">{s.shopping?.code} · {s.shopping?.name}</div><div className="text-[11px] text-muted-foreground">{config.label}</div></div><div className="metric-value">{num(metric==="energyKwh"?s.summary.energyKwh:average(s.history.map(h=>h[metric] as number|null)),3)} <span className="text-[10px] text-muted-foreground">{config.unit}</span></div></div><div className="h-48"><ResponsiveContainer width="100%" height="100%"><LineChart data={s.history}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="timestamp" tickFormatter={labelTime} minTickGap={24} tick={{fontSize:9,fill:"var(--muted-foreground)"}}/><YAxis tick={{fontSize:9,fill:"var(--muted-foreground)"}}/><Tooltip contentStyle={chartTooltipStyle}/><Line type="monotone" dataKey={metric} stroke="var(--accent-cyan)" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div></div>)}</div>}</SectionPanel>
 </InternalPage>
}
function average(values:(number|null|undefined)[]){const v=values.filter((x):x is number=>typeof x==="number"&&Number.isFinite(x));return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function num(v:number|null|undefined,d=1){return v===null||v===undefined?"—":formatNumber(v,{maximumFractionDigits:d})}
function labelTime(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",hour:"2-digit"}).format(d)}
