import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import type { Dispatch, SetStateAction } from "react";
import { Activity, AlertTriangle, Database, Gauge, MonitorCog, Save, Settings, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { liveDashboardService, normalizeSettings } from "@/services/liveDashboardService";
import type { LiveShoppingSummary, ShoppingSettings } from "@/types";
import { LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { InternalPage, SectionPanel, StatusPill } from "@/components/InternalPage";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";
import { formatDateTime } from "@/utils/format";

export const Route = createFileRoute("/configuracoes")({ head: () => ({ meta: [{ title: "Configurações" }] }), component: SettingsPage });

type FormState = {
  baselineKwTr: string; targetKwTr: string; emissionFactorKgCo2Kwh: string; emissionFactorSource: string; emissionFactorReferenceYear: string;
  balanceWarningPct: string; peripheralsWarningPct: string; targetDeviationWarningPct: string; staleAfterMinutes: string;
  baselineReference: string; baselineValidFrom: string; baselineNotes: string;
};

function SettingsPage(){
 const {tick,refreshNow,selectedShoppingCode,setSelectedShoppingCode}=useDashboardRuntime(); const [portfolio,setPortfolio]=useState<LiveShoppingSummary[]>([]); const [settings,setSettings]=useState<ShoppingSettings>(normalizeSettings()); const [form,setForm]=useState<FormState>(toForm(normalizeSettings())); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let alive=true;liveDashboardService.getPortfolio().then(p=>{if(!alive)return;setPortfolio(p.shoppings);if(p.shoppings.length&&!p.shoppings.some(s=>s.code===selectedShoppingCode))setSelectedShoppingCode(p.shoppings[0].code)}).catch(e=>{if(alive)setError(e instanceof Error?e.message:"Falha ao carregar portfólio")});return()=>{alive=false}},[tick,selectedShoppingCode,setSelectedShoppingCode]);
 useEffect(()=>{if(!selectedShoppingCode)return;let alive=true;setLoading(true);liveDashboardService.getSettings(selectedShoppingCode).then(r=>{if(!alive)return;setSettings(r.settings);setForm(toForm(r.settings));setError(null)}).catch(e=>{if(alive)setError(e instanceof Error?e.message:"Falha ao carregar configurações")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[selectedShoppingCode]);
 const current=useMemo(()=>portfolio.find(s=>s.code===selectedShoppingCode)??null,[portfolio,selectedShoppingCode]);
 const save=async()=>{setSaving(true);try{const payload:ShoppingSettings={...settings,baselineKwTr:parseNullable(form.baselineKwTr),targetKwTr:parseNullable(form.targetKwTr),emissionFactorKgCo2Kwh:parseNullable(form.emissionFactorKgCo2Kwh),emissionFactorSource:textOrNull(form.emissionFactorSource),emissionFactorReferenceYear:parseNullable(form.emissionFactorReferenceYear),balanceWarningPct:parseNullable(form.balanceWarningPct),peripheralsWarningPct:parseNullable(form.peripheralsWarningPct),targetDeviationWarningPct:parseNullable(form.targetDeviationWarningPct),staleAfterMinutes:parseNullable(form.staleAfterMinutes),baselineReference:textOrNull(form.baselineReference),baselineValidFrom:textOrNull(form.baselineValidFrom),baselineNotes:textOrNull(form.baselineNotes),reportSettings:settings.reportSettings??{}};const result=await liveDashboardService.saveSettings(selectedShoppingCode,payload);setSettings(result.settings);setForm(toForm(result.settings));refreshNow();toast.success("Configurações salvas e publicadas para os workflows n8n.");}catch(e){toast.error(e instanceof Error?e.message:"Falha ao salvar configurações.")}finally{setSaving(false)}};
 return <InternalPage className="compact-page compact-settings-page"><PageHeader eyebrow="Parâmetros por shopping" title="Configurações" subtitle="Baseline, meta, emissões e limites operacionais são salvos por shopping no PostgreSQL, versionados e consumidos pelos workflows n8n." icon={Settings} right={<Button onClick={save} disabled={saving||loading}><Save className="mr-1.5 h-3.5 w-3.5"/>{saving?"Salvando...":"Salvar alterações"}</Button>}/>
 <div className="panel p-3"><label className="flex w-full max-w-xl flex-col gap-1 text-[10px] font-medium uppercase tracking-[.12em] text-muted-foreground">Shopping<select value={selectedShoppingCode} onChange={e=>setSelectedShoppingCode(e.target.value)} className="mt-1 h-10 rounded-lg border border-border/60 bg-background/55 px-3 text-sm font-normal normal-case tracking-normal text-foreground">{portfolio.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label></div>
 {error&&<div className="rounded-lg border border-[var(--accent-red)]/25 bg-[var(--accent-red)]/8 px-3 py-2 text-xs text-[var(--accent-red)]">{error}</div>}
 {loading?<LoadingBlock h={540}/>:<Tabs defaultValue="desempenho" className="compact-tabs min-h-0 flex-1 space-y-3"><TabsList className="h-auto w-full flex-nowrap justify-start gap-1 overflow-x-auto bg-transparent p-0"><TabsTrigger value="desempenho">Desempenho</TabsTrigger><TabsTrigger value="alertas">Alertas</TabsTrigger><TabsTrigger value="disponibilidade">Disponibilidade</TabsTrigger><TabsTrigger value="sistema">Sistema</TabsTrigger><TabsTrigger value="aparencia">Aparência</TabsTrigger></TabsList>
 <TabsContent value="desempenho" className="compact-tab-content m-0 min-h-0 space-y-3 overflow-y-auto pr-1"><SectionPanel title="Baseline e meta" subtitle="Parâmetros usados por dashboard, análises e relatórios" icon={Gauge}><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Baseline kW/TR" value={form.baselineKwTr} onChange={v=>patch(setForm,"baselineKwTr",v)} unit="kW/TR" placeholder="Não configurado"/><Field label="Meta kW/TR" value={form.targetKwTr} onChange={v=>patch(setForm,"targetKwTr",v)} unit="kW/TR" placeholder="Não configurado"/><Field label="Período / referência do baseline" value={form.baselineReference} onChange={v=>patch(setForm,"baselineReference",v)} placeholder="Ex.: Jan–Mar/2026"/><Field label="Baseline válido desde" value={form.baselineValidFrom} onChange={v=>patch(setForm,"baselineValidFrom",v)} type="date"/><div className="md:col-span-2"><label className="block text-[10px] font-medium uppercase tracking-[.12em] text-muted-foreground">Observações do baseline<Textarea value={form.baselineNotes} onChange={e=>patch(setForm,"baselineNotes",e.target.value)} placeholder="Critério utilizado para definição do baseline" className="mt-1.5 min-h-16 bg-background/55 text-sm normal-case tracking-normal"/></label></div></div></SectionPanel>
 <SectionPanel title="Fator de emissão" subtitle="Aplicado às estimativas de emissões evitadas" icon={Activity}><div className="grid grid-cols-1 gap-4 md:grid-cols-3"><Field label="Fator de emissão" value={form.emissionFactorKgCo2Kwh} onChange={v=>patch(setForm,"emissionFactorKgCo2Kwh",v)} unit="kgCO₂/kWh" placeholder="Não configurado"/><Field label="Fonte do fator" value={form.emissionFactorSource} onChange={v=>patch(setForm,"emissionFactorSource",v)} placeholder="Fonte oficial / documento"/><Field label="Ano / referência" value={form.emissionFactorReferenceYear} onChange={v=>patch(setForm,"emissionFactorReferenceYear",v)} placeholder="2026"/></div></SectionPanel></TabsContent>
 <TabsContent value="alertas" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><SectionPanel title="Limites operacionais" subtitle="Sem valor configurado, o respectivo alerta não é gerado" icon={AlertTriangle}><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Desvio máximo de balanço" value={form.balanceWarningPct} onChange={v=>patch(setForm,"balanceWarningPct",v)} unit="%" placeholder="Não configurado"/><Field label="Periféricos — atenção" value={form.peripheralsWarningPct} onChange={v=>patch(setForm,"peripheralsWarningPct",v)} unit="%" placeholder="Não configurado"/><Field label="Desvio acima da meta" value={form.targetDeviationWarningPct} onChange={v=>patch(setForm,"targetDeviationWarningPct",v)} unit="%" placeholder="Não configurado"/><Field label="Dados desatualizados após" value={form.staleAfterMinutes} onChange={v=>patch(setForm,"staleAfterMinutes",v)} unit="min" placeholder="Não configurado"/></div></SectionPanel></TabsContent>
 <TabsContent value="disponibilidade" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><SectionPanel title="Disponibilidade de dados" subtitle="Derivada automaticamente do cadastro e da última coleta" icon={ShieldCheck}>{current?<div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4"><Availability label="Potência CAG" ok={current.latest?.kpis?.kw_cag!==null&&current.latest?.kpis?.kw_cag!==undefined}/><Availability label="Produção térmica" ok={current.latest?.kpis?.tr_total!==null&&current.latest?.kpis?.tr_total!==undefined}/><Availability label="Periféricos" ok={current.latest?.kpis?.kw_auxiliares!==null&&current.latest?.kpis?.kw_auxiliares!==undefined}/><Availability label="Temperatura externa" ok={current.latest?.kpis?.temperatura_externa_c!==null&&current.latest?.kpis?.temperatura_externa_c!==undefined}/><Availability label="Status de chillers" ok={(current.latest?.kpis?.chillers_status_conhecidos as number|undefined)===current.registry.chillersTotal}/><Availability label="Pontos válidos" ok={(current.latest?.health?.pointsOk??0)===(current.latest?.health?.pointsTotal??current.registry.pointsTotal)} detail={`${current.latest?.health?.pointsOk??0} / ${current.latest?.health?.pointsTotal??current.registry.pointsTotal}`}/></div>:null}</SectionPanel></TabsContent>
 <TabsContent value="sistema" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><SectionPanel title="Integração" subtitle="Informações de operação; credenciais e endpoints não são editáveis pelo cliente" icon={Database}><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4"><Info label="Coleta" value="A cada 5 minutos"/><Info label="API Dashboard" value="Operacional" tone="positive"/><Info label="Shopping" value={current?.code??"—"}/><Info label="Última coleta" value={current?.latest?.collectedAt?formatDateTime(current.latest.collectedAt):"Sem dados"}/><Info label="Versão da configuração" value={settings.version===null?"Não configurada":String(settings.version)}/><Info label="Origem" value={settings.sourceChannel??"—"}/></div></SectionPanel></TabsContent>
 <TabsContent value="aparencia" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><SectionPanel title="Aparência" subtitle="A interface mantém o padrão visual corporativo da aplicação" icon={MonitorCog}><div className="rounded-xl border border-border/55 bg-muted/10 p-4 text-sm text-muted-foreground">Tema escuro, tipografia, espaçamentos e cores permanecem padronizados para todo o portfólio. Não há parâmetros operacionais nesta aba.</div></SectionPanel></TabsContent>
 </Tabs>}
 </InternalPage>
}
function patch(setter:Dispatch<SetStateAction<FormState>>,key:keyof FormState,value:string){setter(prev=>({...prev,[key]:value}))}
function parseNullable(v:string){const t=v.trim().replace(",",".");if(!t)return null;const n=Number(t);if(!Number.isFinite(n))throw new Error(`Valor inválido: ${v}`);return n}
function textOrNull(v:string){const t=v.trim();return t||null}
function toForm(s:ShoppingSettings):FormState{return {baselineKwTr:strKwTr(s.baselineKwTr),targetKwTr:strKwTr(s.targetKwTr),emissionFactorKgCo2Kwh:str(s.emissionFactorKgCo2Kwh),emissionFactorSource:s.emissionFactorSource??"",emissionFactorReferenceYear:str(s.emissionFactorReferenceYear),balanceWarningPct:str(s.balanceWarningPct),peripheralsWarningPct:str(s.peripheralsWarningPct),targetDeviationWarningPct:str(s.targetDeviationWarningPct),staleAfterMinutes:str(s.staleAfterMinutes),baselineReference:s.baselineReference??"",baselineValidFrom:s.baselineValidFrom??"",baselineNotes:s.baselineNotes??""}}
function str(v:number|null|undefined){return v===null||v===undefined?"":String(v)}
function strKwTr(v:number|null|undefined){return v===null||v===undefined?"":v.toFixed(2).replace(".",",")}
function Field({label,value,onChange,unit,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;unit?:string;placeholder?:string;type?:string}){return <label className="block text-[10px] font-medium uppercase tracking-[.12em] text-muted-foreground">{label}<div className="relative mt-1.5"><Input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={`h-10 bg-background/55 text-sm font-normal normal-case tracking-normal ${unit?"pr-24":""}`}/>{unit&&<span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">{unit}</span>}</div></label>}
function Availability({label,ok,detail}:{label:string;ok:boolean;detail?:string}){return <div className="rounded-xl border border-border/55 bg-muted/10 p-4"><div className="flex items-center justify-between gap-2"><div className="text-sm font-medium">{label}</div><StatusPill label={ok?"Disponível":"Indisponível"} tone={ok?"positive":"warning"}/></div>{detail&&<div className="mt-2 text-xs text-muted-foreground">{detail}</div>}</div>}
function Info({label,value,tone="neutral"}:{label:string;value:string;tone?:"positive"|"neutral"}){return <div className="rounded-xl border border-border/55 bg-muted/10 p-4"><div className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">{label}</div><div className="mt-2 flex items-center justify-between gap-2 text-sm font-medium"><span>{value}</span>{tone==="positive"&&<StatusPill label="OK" tone="positive"/>}</div></div>}
