import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, Leaf, Recycle, ShieldCheck, Zap } from "lucide-react";
import { liveDashboardService, asNumber } from "@/services/liveDashboardService";
import type { LiveShoppingSummary } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { InternalPage, SectionPanel, StatCard, StatusPill } from "@/components/InternalPage";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatKwTr, formatNumber } from "@/utils/format";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";

export const Route = createFileRoute("/esg")({ head: () => ({ meta: [{ title: "Energia e Emissões" }] }), component: ESGPage });

function ESGPage(){
 const {tick}=useDashboardRuntime(); const [items,setItems]=useState<LiveShoppingSummary[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;setLoading(true);liveDashboardService.getPortfolio().then(p=>{if(alive)setItems(p.shoppings)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[tick]);
 const totals=useMemo(()=>{const energy=items.map(s=>asNumber(s.today?.energyKwh)).filter((v):v is number=>v!==null);const saved=items.map(s=>asNumber(s.today?.savedKwh)).filter((v):v is number=>v!==null);const avoided=items.map(s=>asNumber(s.today?.avoidedKgCo2)).filter((v):v is number=>v!==null);return {energy:energy.length?energy.reduce((a,b)=>a+b,0):null,saved:saved.length?saved.reduce((a,b)=>a+b,0):null,avoided:avoided.length?avoided.reduce((a,b)=>a+b,0):null,configured:items.filter(s=>s.settings?.baselineKwTr!==null&&s.settings?.emissionFactorKgCo2Kwh!==null).length}},[items]);
 return <InternalPage className="compact-page compact-esg-page"><PageHeader eyebrow="Indicadores disponíveis" title="Energia e Emissões" subtitle="Indicadores calculados somente quando baseline e fator de emissão foram configurados por shopping. Não são exibidos indicadores sociais, de água, resíduos ou outros dados sem fonte." icon={Leaf}/>
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Energia hoje" value={totals.energy===null?"—":formatNumber(totals.energy,{maximumFractionDigits:1})} unit="kWh" icon={Zap} accent="cyan"/><StatCard label="Energia evitada estimada" value={totals.saved===null?"—":formatNumber(totals.saved,{maximumFractionDigits:1})} unit="kWh" icon={Activity} accent="green"/><StatCard label="Emissões evitadas estimadas" value={totals.avoided===null?"—":formatNumber(totals.avoided,{maximumFractionDigits:2})} unit="kgCO₂" icon={Recycle} accent="green"/><StatCard label="Unidades parametrizadas" value={`${totals.configured} / ${items.length}`} icon={ShieldCheck} accent="blue"/></div>
 <SectionPanel title="Energia e emissões por shopping" subtitle="Valores acumulados desde 00:00 respeitando a configuração versionada de cada coleta" icon={Leaf} className="compact-fill-panel" contentClassName="compact-scroll-region">{loading?<LoadingBlock h={380}/>:items.length===0?<EmptyState title="Sem dados disponíveis"/>:<div className="data-table-shell overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Shopping</TableHead><TableHead className="text-right">Energia</TableHead><TableHead className="text-right">Baseline</TableHead><TableHead className="text-right">Meta</TableHead><TableHead className="text-right">Energia evitada</TableHead><TableHead className="text-right">Emissões evitadas</TableHead><TableHead>Configuração</TableHead></TableRow></TableHeader><TableBody>{items.map(s=>{const configured=s.settings?.baselineKwTr!==null&&s.settings?.emissionFactorKgCo2Kwh!==null;return <TableRow key={s.code}><TableCell><div className="font-medium">{s.code} · {s.name}</div></TableCell><TableCell className="metric-value text-right">{num(s.today?.energyKwh,1)} kWh</TableCell><TableCell className="metric-value text-right">{formatKwTr(asNumber(s.settings?.baselineKwTr))} kW/TR</TableCell><TableCell className="metric-value text-right">{formatKwTr(asNumber(s.settings?.targetKwTr))} kW/TR</TableCell><TableCell className="metric-value text-right">{configured?`${num(s.today?.savedKwh,1)} kWh`:"—"}</TableCell><TableCell className="metric-value text-right">{configured?`${num(s.today?.avoidedKgCo2,2)} kgCO₂`:"—"}</TableCell><TableCell><StatusPill label={configured?"Configurado":"Pendente"} tone={configured?"positive":"warning"}/></TableCell></TableRow>})}</TableBody></Table></div>}</SectionPanel>
 </InternalPage>
}
function num(v:unknown,d=1){const n=asNumber(v);return n===null?"—":formatNumber(n,{maximumFractionDigits:d})}
