import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, Download, FileText, Gauge, ShieldCheck, Zap } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { liveDashboardService } from "@/services/liveDashboardService";
import type { HistoryPeriod, LiveShoppingSummary, ShoppingApiResponse } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { InternalPage, chartTooltipStyle } from "@/components/InternalPage";
import { Button } from "@/components/ui/button";
import { formatKwTr, formatNumber } from "@/utils/format";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";

export const Route = createFileRoute("/relatorios")({ head: () => ({ meta: [{ title: "Relatórios" }] }), component: ReportsPage });

function ReportsPage(){
 const {tick,selectedShoppingCode,setSelectedShoppingCode}=useDashboardRuntime(); const [portfolio,setPortfolio]=useState<LiveShoppingSummary[]>([]); const [period,setPeriod]=useState<HistoryPeriod>("7d"); const [data,setData]=useState<ShoppingApiResponse|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;liveDashboardService.getPortfolio().then(p=>{if(!alive)return;setPortfolio(p.shoppings);if(p.shoppings.length&&!p.shoppings.some(s=>s.code===selectedShoppingCode))setSelectedShoppingCode(p.shoppings[0].code)});return()=>{alive=false}},[tick,selectedShoppingCode,setSelectedShoppingCode]);
 useEffect(()=>{if(!selectedShoppingCode)return;let alive=true;setLoading(true);liveDashboardService.getShopping(selectedShoppingCode,period).then(r=>{if(alive)setData(r)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[selectedShoppingCode,period,tick]);
 const configured=!!data?.shopping?.settings?.baselineKwTr; const rows=useMemo(()=>data?.history??[],[data]);
 const exportCsv=()=>{if(!data?.shopping)return;const header=["timestamp","potencia_kw","energia_kwh","producao_tr","frio_trh","kw_tr","perifericos_kw","temperatura_c","qualidade_pct","economia_estimada_kwh","emissoes_evitadas_kgco2"];const csv=[header.join(";"),...rows.map(r=>[r.timestamp,r.kwCag??"",r.energyKwh??"",r.trTotal??"",r.thermalTrh??"",r.kwTr??"",r.kwAux??"",r.temperatureC??"",r.dataQualityPct??"",r.savedKwh??"",r.avoidedKgCo2??""].join(";"))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`ancar-${data.shopping.code}-${period}.csv`;a.click();URL.revokeObjectURL(url)};
 return <InternalPage className="compact-page compact-reports-page"><PageHeader eyebrow="Relatórios operacionais" title="Relatórios" subtitle="Relatórios construídos a partir da telemetria real e da configuração vigente no período." icon={FileText} right={<Button size="sm" onClick={exportCsv} disabled={!data?.history?.length}><Download className="mr-1.5 h-3.5 w-3.5"/>Exportar CSV</Button>}/>
 <div className="reports-control-strip panel"><label>Shopping<select value={selectedShoppingCode} onChange={e=>setSelectedShoppingCode(e.target.value)}>{portfolio.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><div className="segmented-control">{(["24h","7d","30d"] as HistoryPeriod[]).map(p=><button type="button" key={p} data-active={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="ml-auto text-[10px] text-muted-foreground">{rows.length} registros no período</div></div>
 {loading&&!data?<LoadingBlock h={520}/>:!data?.shopping?<EmptyState title="Sem dados para relatório"/>:<div className="reports-workspace-body min-h-0 flex-1">
   <aside className="panel report-library min-h-0 overflow-hidden p-3"><div className="text-xs font-semibold">Biblioteca de relatórios</div><div className="mt-1 text-[10px] text-muted-foreground">Modelos operacionais disponíveis para a unidade selecionada.</div><div className="mt-3 space-y-1.5">{([['24h','Diário operacional'],['7d','Comparativo 7 dias'],['30d','Consolidado 30 dias']] as [HistoryPeriod,string][]).map(([p,label])=><button type="button" key={p} onClick={()=>setPeriod(p)} className={`report-template-row w-full rounded-lg border px-3 py-2 text-left ${period===p?'border-primary/40 bg-primary/8':'border-border/45 bg-muted/10'}`}><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-semibold">{label}</span><span className="text-[9px] text-muted-foreground">{p}</span></div><div className="mt-1 text-[9px] text-muted-foreground">{data.shopping.code} · telemetria histórica</div></button>)}</div><div className="mt-3 rounded-lg border border-border/45 bg-muted/10 p-2.5 text-[10px] text-muted-foreground">Relatórios programados futuros utilizarão os mesmos parâmetros versionados de baseline, meta e alertas definidos no frontend.</div></aside>
   <section className="panel report-preview-panel min-h-0 overflow-hidden p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold">Prévia · {data.shopping.code}</div><div className="mt-0.5 text-[10px] text-muted-foreground">Período {period}</div></div><span className="rounded-full border border-[var(--accent-green)]/25 bg-[var(--accent-green)]/8 px-2 py-1 text-[9px] text-[var(--accent-green)]">Dados reais</span></div><div className="report-preview-metrics mt-2 grid grid-cols-2 gap-1.5 lg:grid-cols-4"><ReportMetric label="Energia" value={data.summary.energyKwh} unit="kWh"/><ReportMetric label="Média" value={data.summary.avgKwTr} unit="kW/TR"/><ReportMetric label="Frio" value={data.summary.thermalTrh} unit="TRh"/><ReportMetric label="Qualidade" value={data.summary.avgDataQualityPct} unit="%"/></div><div className="report-preview-chart mt-2 min-h-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:8,right:8,bottom:2,left:-8}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="timestamp" tickFormatter={v=>timeLabel(String(v))} minTickGap={28} tick={{fontSize:9,fill:'var(--muted-foreground)'}}/><YAxis tick={{fontSize:9,fill:'var(--muted-foreground)'}} width={48}/><Tooltip contentStyle={chartTooltipStyle} labelFormatter={v=>new Date(String(v)).toLocaleString('pt-BR')}/><Line type="monotone" dataKey="kwCag" name="Potência CAG (kW)" stroke="var(--accent-blue)" dot={false} strokeWidth={2} connectNulls/><Line type="monotone" dataKey="trTotal" name="Produção (TR)" stroke="var(--accent-green)" dot={false} strokeWidth={2} connectNulls/></LineChart></ResponsiveContainer></div><div className="mt-2 grid grid-cols-2 gap-1.5"><ReportMetric label="Potência média" value={data.summary.avgKw} unit="kW"/><ReportMetric label="Pico de potência" value={data.summary.maxKw} unit="kW"/>{configured?<><ReportMetric label="Baseline" value={data.shopping.settings.baselineKwTr} unit="kW/TR"/><ReportMetric label="Meta" value={data.shopping.settings.targetKwTr} unit="kW/TR"/></>:<div className="col-span-2 rounded-lg border border-[var(--accent-yellow)]/25 bg-[var(--accent-yellow)]/8 p-2 text-[10px] text-muted-foreground">Configure baseline e fator de emissão para habilitar estimativas no relatório.</div>}</div></section>
 </div>}
 </InternalPage>
}
function num(v:number|null|undefined,d=1){return v===null||v===undefined?"—":formatNumber(v,{maximumFractionDigits:d})}
function ReportMetric({label,value,unit}:{label:string;value:number|null|undefined;unit:string}){const formatted=unit==="kW/TR"?formatKwTr(value):num(value,1);return <div className="rounded-lg border border-border/45 bg-muted/10 px-2.5 py-2"><div className="text-[9px] uppercase tracking-[.1em] text-muted-foreground">{label}</div><div className="mt-1 metric-value text-sm">{formatted} <span className="text-[9px] text-muted-foreground">{unit}</span></div></div>}
function timeLabel(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"}).format(d)}
