import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { CalendarDays, Download, FileBarChart, FileClock, FileText, LoaderCircle } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { liveDashboardService } from "@/services/liveDashboardService";
import { reportService, type ReportPeriodsResponse } from "@/services/reportService";
import type { HistoryPeriod, LiveShoppingSummary, ShoppingApiResponse } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { InternalPage, chartTooltipStyle } from "@/components/InternalPage";
import { Button } from "@/components/ui/button";
import { formatBRL2, formatKwTr, formatNumber } from "@/utils/format";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";
import { buildChartHistory, formatHistoryTick, formatHistoryTooltip, getHistoryTimeDomain, historyTickCount } from "@/utils/history";

export const Route=createFileRoute("/relatorios")({head:()=>({meta:[{title:"Relatórios | ANCAR"}]}),component:ReportsPage});

type ReportType="daily"|"weekly"|"monthly"|"monthlyPortfolio";

function ReportsPage(){
 const {tick,selectedShoppingCode,setSelectedShoppingCode,historyPeriod:period,setHistoryPeriod:setPeriod}=useDashboardRuntime();
 const [portfolio,setPortfolio]=useState<LiveShoppingSummary[]>([]); const [data,setData]=useState<ShoppingApiResponse|null>(null); const [periods,setPeriods]=useState<ReportPeriodsResponse|null>(null); const [portfolioPeriods,setPortfolioPeriods]=useState<ReportPeriodsResponse|null>(null); const [loading,setLoading]=useState(true); const [periodLoading,setPeriodLoading]=useState(false); const [downloadType,setDownloadType]=useState<ReportType|null>(null); const [message,setMessage]=useState(""); const queryRef=useRef("");
 const [dailyDate,setDailyDate]=useState(""); const [weeklyEnd,setWeeklyEnd]=useState(""); const [month,setMonth]=useState(""); const [portfolioMonth,setPortfolioMonth]=useState("");
 useEffect(()=>{let alive=true;liveDashboardService.getPortfolio().then(p=>{if(!alive)return;setPortfolio(p.shoppings);if(p.shoppings.length&&!p.shoppings.some(s=>s.code===selectedShoppingCode))setSelectedShoppingCode(p.shoppings[0].code)}).catch(()=>{});return()=>{alive=false}},[tick,selectedShoppingCode,setSelectedShoppingCode]);
 useEffect(()=>{if(!selectedShoppingCode)return;let alive=true;setPeriodLoading(true);reportService.getPeriods(selectedShoppingCode,"shopping").then(p=>{if(!alive)return;setPeriods(p);const complete=p.latestCompleteDate||p.latestDataDate||"";setDailyDate(v=>v||complete);setWeeklyEnd(v=>v||complete);setMonth(v=>p.availableMonths.some(m=>m.month===v)?v:(p.availableMonths[0]?.month||""))}).catch(e=>{if(alive){setPeriods(null);setMessage(e instanceof Error?e.message:"Não foi possível consultar períodos.")}}).finally(()=>{if(alive)setPeriodLoading(false)});return()=>{alive=false}},[selectedShoppingCode,tick]);
 useEffect(()=>{let alive=true;reportService.getPeriods("","portfolio").then(p=>{if(!alive)return;setPortfolioPeriods(p);setPortfolioMonth(v=>p.availableMonths.some(m=>m.month===v)?v:(p.availableMonths[0]?.month||""))}).catch(()=>{if(alive)setPortfolioPeriods(null)});return()=>{alive=false}},[tick]);
 useEffect(()=>{if(!selectedShoppingCode)return;let alive=true;const key=`${selectedShoppingCode}:${period}`;const queryChanged=queryRef.current!==key;queryRef.current=key;if(queryChanged&&(!data||data.shopping?.code!==selectedShoppingCode||data.period!==period))setLoading(true);liveDashboardService.getShopping(selectedShoppingCode,period).then(r=>{if(alive)setData(r)}).catch(()=>{}).finally(()=>{if(alive&&queryChanged)setLoading(false)});return()=>{alive=false}},[selectedShoppingCode,period,tick]);
 useEffect(()=>{setDailyDate("");setWeeklyEnd("");setMonth("");setMessage("")},[selectedShoppingCode]);
 const rows=useMemo(()=>data?.history??[],[data]); const chart=useMemo(()=>buildChartHistory(rows,period),[rows,period]); const domain=useMemo(()=>getHistoryTimeDomain(period,data?.generatedAt),[period,data?.generatedAt]);
 const exportCsv=()=>{if(!data?.shopping)return;const header=["timestamp","potencia_kw","energia_kwh","producao_tr","frio_trh","kw_tr","custo_energia_brl","energia_acima_meta_kwh","custo_acima_meta_brl","custo_brl_trh","perifericos_kw","temperatura_c","qualidade_pct"];const csv=[header.join(";"),...rows.map(r=>[r.timestamp,r.kwCag??"",r.energyKwh??"",r.trTotal??"",r.thermalTrh??"",r.kwTr??"",r.energyCostBrl??"",r.excessEnergyKwh??"",r.costAboveTargetBrl??"",r.costPerTrhBrl??"",r.kwAux??"",r.temperatureC??"",r.dataQualityPct??""].join(";"))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`ancar-${data.shopping.code}-${period}.csv`;a.click();URL.revokeObjectURL(url)};
 async function download(type:ReportType,anchor:string){if(!anchor){setMessage("Selecione um período disponível.");return}setMessage("");setDownloadType(type);try{if(type==="monthlyPortfolio")await reportService.downloadMonthlyPortfolio(anchor);else await reportService.download(type,selectedShoppingCode,anchor);setMessage("PDF gerado com sucesso.")}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível gerar o relatório.")}finally{setDownloadType(null)}}
 return <InternalPage className="compact-page compact-reports-page"><PageHeader eyebrow="Relatórios consolidados e históricos" title="Relatórios" subtitle="Gere relatórios premium diários, semanais, mensais por shopping e o consolidado mensal do portfólio ANCAR." icon={FileText} right={<Button size="sm" variant="outline" onClick={exportCsv} disabled={!rows.length}><Download className="mr-1.5 h-3.5 w-3.5"/>Exportar CSV</Button>}/>
 <div className="reports-control-strip panel"><label>Shopping<select value={selectedShoppingCode} onChange={e=>setSelectedShoppingCode(e.target.value)}>{portfolio.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><div className="segmented-control">{(["24h","7d","30d"] as HistoryPeriod[]).map(p=><button type="button" key={p} data-active={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="ml-auto text-[10px] text-muted-foreground">{periodLoading?"Consultando períodos...":periods?.earliestDataDate?`Base desde ${formatDate(periods.earliestDataDate)}`:"Sem histórico consolidado"}</div></div>
 <div className="report-generator-grid">
  <ReportGenerator icon={CalendarDays} title="Relatório diário" description="Consolidação de um dia completo, hora a hora." busy={downloadType==="daily"} onDownload={()=>download("daily",dailyDate)}><input type="date" value={dailyDate} max={periods?.latestCompleteDate||undefined} onChange={e=>setDailyDate(e.target.value)}/></ReportGenerator>
  <ReportGenerator icon={FileClock} title="Relatório semanal" description="Sete dias completos encerrando na data selecionada." busy={downloadType==="weekly"} onDownload={()=>download("weekly",weeklyEnd)}><input type="date" value={weeklyEnd} max={periods?.latestCompleteDate||undefined} onChange={e=>setWeeklyEnd(e.target.value)}/></ReportGenerator>
  <ReportGenerator icon={FileBarChart} title="Relatório mensal" description="Mês fechado, inclusive meses históricos já consolidados." busy={downloadType==="monthly"} onDownload={()=>download("monthly",month)}><select value={month} onChange={e=>setMonth(e.target.value)} disabled={!periods?.availableMonths?.length}><option value="">Selecione um mês</option>{periods?.availableMonths.map(m=><option key={m.month} value={m.month}>{monthLabel(m.month)} · {m.daysWithData} dias com dados</option>)}</select><div className="report-history-note">Até os 6 meses fechados mais recentes existentes na base.</div></ReportGenerator>
  <ReportGenerator icon={FileBarChart} title="Mensal · Portfólio ANCAR" description="Consolidado executivo de todos os shoppings com rankings e métricas normalizadas por área." busy={downloadType==="monthlyPortfolio"} onDownload={()=>download("monthlyPortfolio",portfolioMonth)}><select value={portfolioMonth} onChange={e=>setPortfolioMonth(e.target.value)} disabled={!portfolioPeriods?.availableMonths?.length}><option value="">Selecione um mês</option>{portfolioPeriods?.availableMonths.map(m=><option key={m.month} value={m.month}>{monthLabel(m.month)} · {m.shoppingsWithData??"—"} shoppings com dados</option>)}</select><div className="report-history-note">Até os 6 meses fechados mais recentes existentes no portfólio.</div></ReportGenerator>
 </div>
 {message&&<div className="report-message">{message}</div>}
 {loading&&(!data||data.period!==period)?<LoadingBlock h={420}/>:!data?.shopping?<EmptyState title="Sem dados para relatório"/>:<div className="reports-workspace-body min-h-0 flex-1">
  <aside className="panel report-library min-h-0 overflow-hidden p-3"><div className="text-xs font-semibold">Conteúdo dos PDFs</div><div className="mt-1 text-[10px] text-muted-foreground">Design premium A4 homologado, com análises técnicas, econômicas, climáticas e por área.</div><div className="mt-3 space-y-1.5"><Template title="Resumo e Indicadores" detail="Energia, TRh, eficiência, metas, custos e métricas por m²"/><Template title="Clima, Carga e Operação" detail="Correlação com temperatura, carga térmica e chillers ativos"/><Template title="Chillers e Infraestrutura" detail="Horas, partidas, energia, TRh, kW/TR, periféricos e cobertura"/><Template title="Oportunidades e Qualidade" detail="Baixa carga, picos, custo acima da meta, heatmaps e metodologia"/></div></aside>
  <section className="panel report-preview-panel min-h-0 overflow-hidden p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold">Prévia executiva · {data.shopping.code}</div><div className="mt-0.5 text-[10px] text-muted-foreground">Período visual atual: {period}</div></div><span className="rounded-full border border-[var(--accent-green)]/25 bg-[var(--accent-green)]/8 px-2 py-1 text-[9px] text-[var(--accent-green)]">Dados reais</span></div>
   <div className="report-preview-metrics mt-2 grid grid-cols-2 gap-1.5 lg:grid-cols-6"><ReportMetric label="Energia" value={data.summary.energyKwh==null?"—":`${formatNumber(data.summary.energyKwh/1000,{maximumFractionDigits:2})} MWh`}/><ReportMetric label="Eficiência média" value={`${formatKwTr(data.summary.avgKwTr)} kW/TR`}/><ReportMetric label="Custo energético" value={formatBRL2(data.summary.energyCostBrl)}/><ReportMetric label="Custo acima meta" value={formatBRL2(data.summary.costAboveTargetBrl)}/><ReportMetric label="R$/TRh" value={formatBRL2(data.summary.costPerTrhBrl)}/><ReportMetric label="Tempo na meta" value={data.summary.targetTimePct==null?"—":`${formatNumber(data.summary.targetTimePct,{maximumFractionDigits:1})}%`}/></div>
   <div className="report-preview-chart mt-2 min-h-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:8,right:8,bottom:2,left:-8}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="chartTimestamp" type="number" scale="time" domain={domain} tickCount={historyTickCount(period)} tickFormatter={v=>formatHistoryTick(Number(v),period)} minTickGap={24} tick={{fontSize:9,fill:"var(--muted-foreground)"}} allowDataOverflow/><YAxis tick={{fontSize:9,fill:"var(--muted-foreground)"}} width={48}/><Tooltip contentStyle={chartTooltipStyle} labelFormatter={v=>formatHistoryTooltip(typeof v==="number"?v:Number(v))}/><Line isAnimationActive={false} type="linear" dataKey="kwTr" name="Eficiência (kW/TR)" stroke="var(--accent-green)" dot={false} strokeWidth={2}/><Line isAnimationActive={false} type="linear" dataKey="costAboveTargetBrl" name="Custo acima da meta (R$)" stroke="var(--accent-yellow)" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div>
   <div className="mt-2 grid grid-cols-2 gap-1.5 lg:grid-cols-4"><ReportMetric label="Meta CAG" value={data.shopping.settings.targetKwTr==null?"—":`${formatKwTr(data.shopping.settings.targetKwTr)} kW/TR`}/><ReportMetric label="Meta Chillers" value={data.shopping.settings.targetChillerKwTr==null?"—":`${formatKwTr(data.shopping.settings.targetChillerKwTr)} kW/TR`}/><ReportMetric label="Tarifa" value={data.shopping.settings.energyTariffBrlMwh==null?"—":`R$ ${formatNumber(data.shopping.settings.energyTariffBrlMwh,{maximumFractionDigits:2})}/MWh`}/><ReportMetric label="Qualidade média" value={data.summary.avgDataQualityPct==null?"—":`${formatNumber(data.summary.avgDataQualityPct,{maximumFractionDigits:1})}%`}/></div>
  </section></div>}
 </InternalPage>}
function ReportGenerator({icon:Icon,title,description,busy,onDownload,children}:{icon:typeof FileText;title:string;description:string;busy:boolean;onDownload:()=>void;children:ReactNode}){return <section className="panel report-generator-card"><div className="report-generator-head"><div className="report-generator-icon"><Icon/></div><div><h3>{title}</h3><p>{description}</p></div></div><div className="report-generator-control">{children}</div><Button size="sm" onClick={onDownload} disabled={busy}>{busy?<LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin"/>:<Download className="mr-1.5 h-3.5 w-3.5"/>}{busy?"Gerando PDF...":"Baixar PDF"}</Button></section>}
function Template({title,detail}:{title:string;detail:string}){return <div className="rounded-lg border border-border/45 bg-muted/10 px-3 py-2"><div className="flex items-center gap-2"><FileText className="h-3.5 w-3.5 text-primary"/><span className="text-[11px] font-semibold">{title}</span></div><div className="mt-1 text-[9px] text-muted-foreground">{detail}</div></div>}
function ReportMetric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-border/45 bg-muted/10 px-2.5 py-2"><div className="text-[9px] uppercase tracking-[.08em] text-muted-foreground">{label}</div><div className="metric-value mt-1 text-sm">{value}</div></div>}
function formatDate(value:string){const [y,m,d]=value.slice(0,10).split("-");return y&&m&&d?`${d}/${m}/${y}`:value}
function monthLabel(value:string){const [y,m]=value.split("-");const names=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];return `${names[Math.max(0,Number(m)-1)]||m} de ${y}`}
