import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, Download, FileText, Gauge, ShieldCheck, Zap } from "lucide-react";
import { liveDashboardService } from "@/services/liveDashboardService";
import type { HistoryPeriod, LiveShoppingSummary, ShoppingApiResponse } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { FilterBar, InternalPage, SectionPanel, StatCard } from "@/components/InternalPage";
import { Button } from "@/components/ui/button";
import { formatKwTr, formatNumber } from "@/utils/format";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";

export const Route = createFileRoute("/relatorios")({ head: () => ({ meta: [{ title: "Relatórios" }] }), component: ReportsPage });

function ReportsPage(){
 const {tick,selectedShoppingCode,setSelectedShoppingCode}=useDashboardRuntime(); const [portfolio,setPortfolio]=useState<LiveShoppingSummary[]>([]); const [period,setPeriod]=useState<HistoryPeriod>("7d"); const [data,setData]=useState<ShoppingApiResponse|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;liveDashboardService.getPortfolio().then(p=>{if(!alive)return;setPortfolio(p.shoppings);if(p.shoppings.length&&!p.shoppings.some(s=>s.code===selectedShoppingCode))setSelectedShoppingCode(p.shoppings[0].code)});return()=>{alive=false}},[tick,selectedShoppingCode,setSelectedShoppingCode]);
 useEffect(()=>{if(!selectedShoppingCode)return;let alive=true;setLoading(true);liveDashboardService.getShopping(selectedShoppingCode,period).then(r=>{if(alive)setData(r)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[selectedShoppingCode,period,tick]);
 const configured=!!data?.shopping?.settings?.baselineKwTr; const rows=useMemo(()=>data?.history??[],[data]);
 const exportCsv=()=>{if(!data?.shopping)return;const header=["timestamp","potencia_kw","energia_kwh","producao_tr","frio_trh","kw_tr","perifericos_kw","temperatura_c","qualidade_pct","economia_estimada_kwh","emissoes_evitadas_kgco2"];const csv=[header.join(";"),...rows.map(r=>[r.timestamp,r.kwCag??"",r.energyKwh??"",r.trTotal??"",r.thermalTrh??"",r.kwTr??"",r.kwAux??"",r.temperatureC??"",r.dataQualityPct??"",r.savedKwh??"",r.avoidedKgCo2??""].join(";"))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`ancar-${data.shopping.code}-${period}.csv`;a.click();URL.revokeObjectURL(url)};
 return <InternalPage className="compact-page compact-reports-page"><PageHeader eyebrow="Relatórios operacionais" title="Relatórios" subtitle="Prévia baseada na telemetria histórica. Os mesmos parâmetros de baseline, meta e alertas configurados no frontend são usados nos cálculos." icon={FileText} right={<Button onClick={exportCsv} disabled={!data?.history?.length}><Download className="mr-1.5 h-3.5 w-3.5"/>Exportar CSV</Button>}/>
 <FilterBar><label className="flex w-full flex-col sm:min-w-[220px] sm:w-auto gap-1 text-[10px] uppercase tracking-[.12em] text-muted-foreground">Shopping<select value={selectedShoppingCode} onChange={e=>setSelectedShoppingCode(e.target.value)} className="h-9 rounded-lg border border-border/60 bg-background/55 px-2.5 text-sm normal-case tracking-normal text-foreground">{portfolio.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><div className="segmented-control w-full self-end sm:w-auto">{(["24h","7d","30d"] as HistoryPeriod[]).map(p=><button type="button" key={p} data-active={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div></FilterBar>
 {loading&&!data?<LoadingBlock h={520}/>:!data?.shopping?<EmptyState title="Sem dados para relatório"/>:<div className="reports-workspace compact-scroll-region min-h-0 space-y-3">
 <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Energia no período" value={num(data.summary.energyKwh,1)} unit="kWh" icon={Zap} accent="cyan"/><StatCard label="Frio acumulado" value={num(data.summary.thermalTrh,1)} unit="TRh" icon={Activity} accent="blue"/><StatCard label="Média kW/TR" value={formatKwTr(data.summary.avgKwTr)} unit="kW/TR" icon={Gauge} accent="green"/><StatCard label="Qualidade média" value={num(data.summary.avgDataQualityPct,1)} unit="%" icon={ShieldCheck} accent="purple"/></div>
 <div className="grid grid-cols-1 gap-4 xl:grid-cols-2"><SectionPanel title="Resumo de desempenho" subtitle={`Período ${period}`} icon={Activity}><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><ReportMetric label="Potência média" value={data.summary.avgKw} unit="kW"/><ReportMetric label="Pico de potência" value={data.summary.maxKw} unit="kW"/><ReportMetric label="Produção média" value={data.summary.avgTr} unit="TR"/><ReportMetric label="Pico de produção" value={data.summary.maxTr} unit="TR"/><ReportMetric label="Periféricos médios" value={data.summary.avgAuxKw} unit="kW"/><ReportMetric label="Energia total" value={data.summary.energyKwh} unit="kWh"/></div></SectionPanel>
 <SectionPanel title="Baseline e emissões" subtitle="Estimativas somente quando os parâmetros foram configurados" icon={FileText}>{configured?<div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><ReportMetric label="Baseline" value={data.shopping.settings.baselineKwTr} unit="kW/TR"/><ReportMetric label="Meta" value={data.shopping.settings.targetKwTr} unit="kW/TR"/><ReportMetric label="Energia evitada estimada" value={data.summary.savedKwh} unit="kWh"/><ReportMetric label="Emissões evitadas estimadas" value={data.summary.avoidedKgCo2} unit="kgCO₂"/></div>:<div className="rounded-xl border border-[var(--accent-yellow)]/25 bg-[var(--accent-yellow)]/8 p-4 text-sm text-muted-foreground">Configure baseline e fator de emissão para habilitar estimativas de energia e emissões evitadas.</div>}</SectionPanel></div>
 <SectionPanel title="Relatórios programados" subtitle="Estrutura preparada para a próxima etapa" icon={FileText}><p className="text-sm text-muted-foreground">Quando os relatórios automáticos forem ativados, eles consultarão a mesma configuração versionada por shopping utilizada por dashboard, alertas e análises. Nenhum parâmetro ficará hardcoded nos workflows.</p></SectionPanel>
 </div>}
 </InternalPage>
}
function num(v:number|null|undefined,d=1){return v===null||v===undefined?"—":formatNumber(v,{maximumFractionDigits:d})}
function ReportMetric({label,value,unit}:{label:string;value:number|null|undefined;unit:string}){const formatted=unit==="kW/TR"?formatKwTr(value):num(value,1);return <div className="rounded-xl border border-border/55 bg-muted/10 p-3"><div className="text-[10px] uppercase tracking-[.1em] text-muted-foreground">{label}</div><div className="mt-1.5 metric-value text-xl">{formatted} <span className="text-[10px] text-muted-foreground">{unit}</span></div></div>}
