import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { BadgeDollarSign, Download, FileText, Gauge, Zap } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { liveDashboardService } from "@/services/liveDashboardService";
import type { HistoryPeriod, LiveShoppingSummary, ShoppingApiResponse } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { InternalPage, chartTooltipStyle } from "@/components/InternalPage";
import { Button } from "@/components/ui/button";
import { formatBRL2, formatKwTr, formatNumber } from "@/utils/format";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";
import { buildChartHistory, formatHistoryTick, formatHistoryTooltip, getHistoryTimeDomain, historyTickCount } from "@/utils/history";

export const Route=createFileRoute("/relatorios")({head:()=>({meta:[{title:"Relatórios"}]}),component:ReportsPage});
function ReportsPage(){
 const {tick,selectedShoppingCode,setSelectedShoppingCode,historyPeriod:period,setHistoryPeriod:setPeriod}=useDashboardRuntime(); const [portfolio,setPortfolio]=useState<LiveShoppingSummary[]>([]); const [data,setData]=useState<ShoppingApiResponse|null>(null); const [loading,setLoading]=useState(true); const queryRef=useRef("");
 useEffect(()=>{let alive=true;liveDashboardService.getPortfolio().then(p=>{if(!alive)return;setPortfolio(p.shoppings);if(p.shoppings.length&&!p.shoppings.some(s=>s.code===selectedShoppingCode))setSelectedShoppingCode(p.shoppings[0].code)});return()=>{alive=false}},[tick,selectedShoppingCode,setSelectedShoppingCode]);
 useEffect(()=>{if(!selectedShoppingCode)return;let alive=true;const key=`${selectedShoppingCode}:${period}`;const queryChanged=queryRef.current!==key;queryRef.current=key;if(queryChanged&&(!data||data.shopping?.code!==selectedShoppingCode||data.period!==period))setLoading(true);liveDashboardService.getShopping(selectedShoppingCode,period).then(r=>{if(alive)setData(r)}).catch(()=>{}).finally(()=>{if(alive&&queryChanged)setLoading(false)});return()=>{alive=false}},[selectedShoppingCode,period,tick]);
 const rows=useMemo(()=>data?.history??[],[data]); const chart=useMemo(()=>buildChartHistory(rows,period),[rows,period]); const domain=useMemo(()=>getHistoryTimeDomain(period,data?.generatedAt),[period,data?.generatedAt]);
 const exportCsv=()=>{if(!data?.shopping)return;const header=["timestamp","potencia_kw","energia_kwh","producao_tr","frio_trh","kw_tr","custo_energia_brl","energia_acima_meta_kwh","custo_acima_meta_brl","custo_brl_trh","perifericos_kw","temperatura_c","qualidade_pct"];const csv=[header.join(";"),...rows.map(r=>[r.timestamp,r.kwCag??"",r.energyKwh??"",r.trTotal??"",r.thermalTrh??"",r.kwTr??"",r.energyCostBrl??"",r.excessEnergyKwh??"",r.costAboveTargetBrl??"",r.costPerTrhBrl??"",r.kwAux??"",r.temperatureC??"",r.dataQualityPct??""].join(";"))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`ancar-${data.shopping.code}-${period}.csv`;a.click();URL.revokeObjectURL(url)};
 return <InternalPage className="compact-page compact-reports-page"><PageHeader eyebrow="Relatórios operacionais e econômicos" title="Relatórios" subtitle="Exporte telemetria, eficiência e indicadores econômicos calculados com a configuração vigente." icon={FileText} right={<Button size="sm" onClick={exportCsv} disabled={!rows.length}><Download className="mr-1.5 h-3.5 w-3.5"/>Exportar CSV</Button>}/>
 <div className="reports-control-strip panel"><label>Shopping<select value={selectedShoppingCode} onChange={e=>setSelectedShoppingCode(e.target.value)}>{portfolio.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><div className="segmented-control">{(["24h","7d","30d"] as HistoryPeriod[]).map(p=><button type="button" key={p} data-active={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="ml-auto text-[10px] text-muted-foreground">{rows.length} registros no período</div></div>
 {loading&&(!data||data.period!==period)?<LoadingBlock h={520}/>:!data?.shopping?<EmptyState title="Sem dados para relatório"/>:<div className="reports-workspace-body min-h-0 flex-1">
  <aside className="panel report-library min-h-0 overflow-hidden p-3"><div className="text-xs font-semibold">Biblioteca de relatórios</div><div className="mt-1 text-[10px] text-muted-foreground">Modelos baseados em telemetria e parâmetros do cliente.</div><div className="mt-3 space-y-1.5"><Template title="Resumo Executivo" detail="Eficiência, custo, oportunidade e qualidade"/><Template title="Desempenho da CAG" detail="Potência, produção, Meta CAG e tempo na meta"/><Template title="Análise dos Chillers" detail="Eficiência individual e Meta Chillers"/><Template title="Energia e Custos" detail="Consumo, tarifa, custo e R$/TRh"/><Template title="Dados detalhados (CSV)" detail="Série histórica para análise externa"/></div></aside>
  <section className="panel report-preview-panel min-h-0 overflow-hidden p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold">Prévia executiva · {data.shopping.code}</div><div className="mt-0.5 text-[10px] text-muted-foreground">Período {period}</div></div><span className="rounded-full border border-[var(--accent-green)]/25 bg-[var(--accent-green)]/8 px-2 py-1 text-[9px] text-[var(--accent-green)]">Dados reais</span></div>
   <div className="report-preview-metrics mt-2 grid grid-cols-2 gap-1.5 lg:grid-cols-6"><ReportMetric label="Energia" value={data.summary.energyKwh==null?"—":`${formatNumber(data.summary.energyKwh/1000,{maximumFractionDigits:2})} MWh`}/><ReportMetric label="Eficiência média" value={`${formatKwTr(data.summary.avgKwTr)} kW/TR`}/><ReportMetric label="Custo energético" value={formatBRL2(data.summary.energyCostBrl)}/><ReportMetric label="Custo acima meta" value={formatBRL2(data.summary.costAboveTargetBrl)}/><ReportMetric label="R$/TRh" value={formatBRL2(data.summary.costPerTrhBrl)}/><ReportMetric label="Tempo na meta" value={data.summary.targetTimePct==null?"—":`${formatNumber(data.summary.targetTimePct,{maximumFractionDigits:1})}%`}/></div>
   <div className="report-preview-chart mt-2 min-h-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:8,right:8,bottom:2,left:-8}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="chartTimestamp" type="number" scale="time" domain={domain} tickCount={historyTickCount(period)} tickFormatter={v=>formatHistoryTick(Number(v),period)} minTickGap={24} tick={{fontSize:9,fill:"var(--muted-foreground)"}} allowDataOverflow/><YAxis tick={{fontSize:9,fill:"var(--muted-foreground)"}} width={48}/><Tooltip contentStyle={chartTooltipStyle} labelFormatter={v=>formatHistoryTooltip(typeof v==="number"?v:Number(v))}/><Line isAnimationActive={false} type="linear" dataKey="kwTr" name="Eficiência (kW/TR)" stroke="var(--accent-green)" dot={false} strokeWidth={2}/><Line isAnimationActive={false} type="linear" dataKey="costAboveTargetBrl" name="Custo acima da meta (R$)" stroke="var(--accent-yellow)" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div>
   <div className="mt-2 grid grid-cols-2 gap-1.5 lg:grid-cols-4"><ReportMetric label="Meta CAG" value={data.shopping.settings.targetKwTr==null?"—":`${formatKwTr(data.shopping.settings.targetKwTr)} kW/TR`}/><ReportMetric label="Meta Chillers" value={data.shopping.settings.targetChillerKwTr==null?"—":`${formatKwTr(data.shopping.settings.targetChillerKwTr)} kW/TR`}/><ReportMetric label="Tarifa" value={data.shopping.settings.energyTariffBrlMwh==null?"—":`R$ ${formatNumber(data.shopping.settings.energyTariffBrlMwh,{maximumFractionDigits:2})}/MWh`}/><ReportMetric label="Qualidade média" value={data.summary.avgDataQualityPct==null?"—":`${formatNumber(data.summary.avgDataQualityPct,{maximumFractionDigits:1})}%`}/></div>
  </section>
 </div>}
 </InternalPage>}
function Template({title,detail}:{title:string;detail:string}){return <div className="rounded-lg border border-border/45 bg-muted/10 px-3 py-2"><div className="flex items-center gap-2"><FileText className="h-3.5 w-3.5 text-primary"/><span className="text-[11px] font-semibold">{title}</span></div><div className="mt-1 text-[9px] text-muted-foreground">{detail}</div></div>}
function ReportMetric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-border/45 bg-muted/10 px-2.5 py-2"><div className="text-[9px] uppercase tracking-[.08em] text-muted-foreground">{label}</div><div className="metric-value mt-1 text-sm">{value}</div></div>}
