import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowLeft, BadgeDollarSign, Fan, Gauge, Snowflake, Thermometer, Zap } from "lucide-react";
import { CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { dashboardService } from "@/services/dashboardService";
import type { HistoryPeriod, ShoppingApiResponse } from "@/types";
import { EmptyState, LoadingBlock, PageHeader } from "@/components/ui-helpers";
import { InternalPage, SectionPanel, StatCard, StatusPill, chartTooltipStyle } from "@/components/InternalPage";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { formatBRL2, formatDateTime, formatKwTr, formatNumber } from "@/utils/format";
import { asNumber, buildCurrentAlerts, mapLiveShoppingToLegacy } from "@/services/liveDashboardService";
import { useDashboardRuntime } from "@/contexts/dashboard-runtime-context";
import { buildChartHistory, formatHistoryTick, formatHistoryTooltip, getHistoryTimeDomain, historyTickCount } from "@/utils/history";
import { targetDeviation } from "@/utils/economics";

export const Route = createFileRoute("/shoppings/$shoppingId")({ head: ({ params }) => ({ meta: [{ title: `${params.shoppingId.toUpperCase()} — Detalhe do Shopping` }] }), component: ShoppingDetailPage });

function ShoppingDetailPage() {
  const { shoppingId } = Route.useParams();
  const { tick, historyPeriod: period, setHistoryPeriod: setPeriod } = useDashboardRuntime();
  const [data, setData] = useState<ShoppingApiResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const queryRef=useRef("");
  useEffect(()=>{let alive=true;const key=`${shoppingId}:${period}`;const queryChanged=queryRef.current!==key;queryRef.current=key;if(queryChanged&&!(data?.shopping&&data.period===period))setLoading(true);dashboardService.getShoppingById(shoppingId,period).then(r=>{if(alive){setData(r);setError(r?null:"Shopping não encontrado.")}}).catch(e=>{if(alive&&!(data?.shopping&&data.period===period))setError(e instanceof Error?e.message:"Falha ao carregar dados.")}).finally(()=>{if(alive&&queryChanged)setLoading(false)});return()=>{alive=false}},[shoppingId,period,tick]);
  if(loading&&(!data||data.period!==period))return <LoadingBlock h={760}/>; if(!data?.shopping)return <EmptyState title="Shopping indisponível" description={error??"Não foi possível consultar esta unidade."}/>;

  const raw=data.shopping, shopping=mapLiveShoppingToLegacy(raw), k=raw.latest?.kpis??{}, settings=raw.settings;
  const equipments=Object.entries(k.equipamentos??{}).map(([key,eq])=>({key,...eq})).filter(eq=>String(eq.equipmentType??"").startsWith("chiller"));
  const chartHistory=buildChartHistory(data.history,period), historyDomain=getHistoryTimeDomain(period,data.generatedAt);
  const currentKwTr=shopping.efficiencyKWTR, chillerKwTr=asNumber(k.kw_tr_chillers), cagDev=targetDeviation(currentKwTr,settings.targetKwTr), chillerDev=targetDeviation(chillerKwTr,settings.targetChillerKwTr);
  const alerts=buildCurrentAlerts([raw]);
  return <InternalPage className="compact-page compact-detail-page">
    <PageHeader eyebrow={`${shopping.code} · ${shopping.city}/${shopping.stateCode}`} title={shopping.name} subtitle={raw.latest?.collectedAt?`Última coleta: ${formatDateTime(raw.latest.collectedAt)}`:"Sem coleta disponível"} icon={Activity} right={<Button variant="outline" size="sm" asChild><Link to="/shoppings"><ArrowLeft className="mr-1.5 h-3.5 w-3.5"/>Voltar</Link></Button>}/>
    {error&&<div className="rounded-lg border border-[var(--accent-yellow)]/25 bg-[var(--accent-yellow)]/8 px-3 py-2 text-xs text-[var(--accent-yellow)]">{error}</div>}
    <div className="grid grid-cols-2 gap-2.5 md:grid-cols-3 xl:grid-cols-6"><StatCard label="Potência CAG" value={num(shopping.powerKW,1)} unit="kW" icon={Zap} accent="cyan"/><StatCard label="Produção térmica" value={num(shopping.thermalLoadTR,1)} unit="TR" icon={Activity} accent="blue"/><StatCard label="Eficiência CAG" value={formatKwTr(currentKwTr)} unit="kW/TR" icon={Gauge} accent="green"/><StatCard label="Chillers ativos" value={shopping.activeChillers==null?"—":`${shopping.activeChillers}/${shopping.chillersTotal}`} icon={Snowflake} accent="purple"/><StatCard label="Periféricos" value={num(shopping.peripheralKW,1)} unit="kW" icon={Fan} accent="yellow"/><StatCard label="Temp. externa" value={num(shopping.temperatureC,1)} unit="°C" icon={Thermometer} accent="orange"/></div>
    <Tabs defaultValue="geral" className="compact-tabs min-h-0 flex-1 space-y-3"><TabsList className="h-auto w-full flex-nowrap justify-start gap-1 overflow-x-auto bg-transparent p-0"><TabsTrigger value="geral">Visão Geral</TabsTrigger><TabsTrigger value="chillers">Chillers</TabsTrigger><TabsTrigger value="qualidade">Qualidade</TabsTrigger><TabsTrigger value="metas">Metas</TabsTrigger></TabsList>
      <TabsContent value="geral" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><div className="grid gap-3 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.75fr)]">
        <SectionPanel title="Comportamento da CAG" subtitle="Potência, produção e eficiência no período" icon={Activity} right={<div className="segmented-control">{(["24h","7d","30d"] as HistoryPeriod[]).map(p=><button type="button" key={p} data-active={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div>}>
          <div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartHistory}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="chartTimestamp" type="number" scale="time" domain={historyDomain} tickCount={historyTickCount(period)} tickFormatter={v=>formatHistoryTick(Number(v),period)} minTickGap={24} tick={{fontSize:10,fill:"var(--muted-foreground)"}} allowDataOverflow/><YAxis yAxisId="left" tick={{fontSize:10,fill:"var(--muted-foreground)"}}/><YAxis yAxisId="right" orientation="right" tick={{fontSize:10,fill:"var(--muted-foreground)"}}/><Tooltip contentStyle={chartTooltipStyle} labelFormatter={v=>formatHistoryTooltip(typeof v==="number"?v:Number(v))}/><Line isAnimationActive={false} yAxisId="left" type="linear" dataKey="kwCag" name="Potência CAG (kW)" stroke="var(--accent-cyan)" dot={false} strokeWidth={2}/><Line isAnimationActive={false} yAxisId="left" type="linear" dataKey="trTotal" name="Produção (TR)" stroke="var(--accent-blue)" dot={false} strokeWidth={2}/><Line isAnimationActive={false} yAxisId="right" type="linear" dataKey="kwTr" name="Eficiência (kW/TR)" stroke="var(--accent-green)" dot={false} strokeWidth={2}/></ComposedChart></ResponsiveContainer></div>
        </SectionPanel>
        <div className="space-y-3"><SectionPanel title="Performance vs Metas" icon={Gauge}><Goal label="CAG" current={currentKwTr} target={settings.targetKwTr} deviation={cagDev}/><div className="mt-4"><Goal label="Chillers" current={chillerKwTr} target={settings.targetChillerKwTr} deviation={chillerDev}/></div></SectionPanel><SectionPanel title={`Resumo Econômico · ${period}`} icon={BadgeDollarSign}><div className="grid grid-cols-2 gap-2"><Mini label="Custo energético" value={formatBRL2(data.summary.energyCostBrl)}/><Mini label="Custo acima da meta" value={formatBRL2(data.summary.costAboveTargetBrl)} warn/><Mini label="Energia" value={data.summary.energyKwh==null?"—":`${formatNumber(data.summary.energyKwh/1000,{maximumFractionDigits:2})} MWh`}/><Mini label="R$/TRh" value={data.summary.costPerTrhBrl==null?"—":formatBRL2(data.summary.costPerTrhBrl)}/><Mini label="Tempo na meta" value={data.summary.targetTimePct==null?"—":`${formatNumber(data.summary.targetTimePct,{maximumFractionDigits:1})}%`}/><Mini label="Tarifa" value={settings.energyTariffBrlMwh==null?"—":`R$ ${formatNumber(settings.energyTariffBrlMwh,{maximumFractionDigits:2})}/MWh`}/></div></SectionPanel></div>
      </div></TabsContent>
      <TabsContent value="chillers" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><SectionPanel title="Desempenho dos Chillers" subtitle="Eficiência individual, meta e oportunidade econômica estimada" icon={Snowflake}>{equipments.length?<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-muted-foreground"><tr className="border-b border-border"><th className="py-2">Chiller</th><th>Status</th><th className="text-right">kW</th><th className="text-right">TR</th><th className="text-right">kW/TR</th><th className="text-right">Meta</th><th className="text-right">Desvio</th><th className="text-right">Oportunidade</th></tr></thead><tbody>{equipments.map(eq=><tr key={eq.key} className="border-b border-border/40"><td className="py-2.5 font-semibold">{labelEquipment(eq.key)}</td><td><StatusPill label={eq.status===true?"Ligado":eq.status===false?"Desligado":"Sem status"} tone={eq.status===true?"positive":"neutral"}/></td><td className="text-right">{num(asNumber(eq.kw),1)}</td><td className="text-right">{num(asNumber(eq.tr),1)}</td><td className="metric-value text-right">{formatKwTr(asNumber(eq.kw_tr))}</td><td className="text-right">{formatKwTr(asNumber(eq.target_kw_tr)??settings.targetChillerKwTr)}</td><td className={`text-right font-semibold ${asNumber(eq.target_deviation_pct)!==null&&asNumber(eq.target_deviation_pct)!<=0?"text-[var(--accent-green)]":"text-[var(--accent-red)]"}`}>{pct(asNumber(eq.target_deviation_pct))}</td><td className="text-right">{asNumber(eq.opportunity_brl_h)==null?"—":`${formatBRL2(asNumber(eq.opportunity_brl_h))}/h`}</td></tr>)}</tbody></table></div>:<EmptyState title="Sem dados de chillers"/>}</SectionPanel></TabsContent>
      <TabsContent value="qualidade" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><div className="grid gap-3 md:grid-cols-2"><SectionPanel title="Qualidade da aquisição" icon={Activity}><div className="grid grid-cols-2 gap-2"><Mini label="Pontos OK" value={`${raw.latest?.health?.pointsOk??0}/${raw.latest?.health?.pointsTotal??raw.registry.pointsTotal}`}/><Mini label="Retries recuperados" value={String(raw.latest?.health?.retryRecoveredPoints??0)}/><Mini label="Falhas finais" value={String(raw.latest?.health?.failedAfterRetries??0)}/><Mini label="Qualidade" value={`${shopping.dataQualityPct.toFixed(0)}%`}/></div></SectionPanel><SectionPanel title="Alertas ativos" icon={Activity}>{alerts.length?<div className="space-y-2">{alerts.map(a=><div key={a.id} className="rounded-lg border border-border/45 bg-muted/10 p-2 text-xs"><div className="font-semibold">{a.title}</div><div className="mt-1 text-[10px] text-muted-foreground">{a.description}</div></div>)}</div>:<div className="text-xs text-muted-foreground">Nenhum alerta ativo.</div>}</SectionPanel></div></TabsContent>
      <TabsContent value="metas" className="compact-tab-content m-0 min-h-0 overflow-y-auto pr-1"><SectionPanel title="Parâmetros do cliente" subtitle="A edição é centralizada na tela Configurações" icon={Gauge}><div className="grid gap-3 md:grid-cols-3"><Mini label="Meta CAG" value={settings.targetKwTr==null?"—":`${formatKwTr(settings.targetKwTr)} kW/TR`}/><Mini label="Meta Chillers" value={settings.targetChillerKwTr==null?"—":`${formatKwTr(settings.targetChillerKwTr)} kW/TR`}/><Mini label="Tarifa" value={settings.energyTariffBrlMwh==null?"—":`R$ ${formatNumber(settings.energyTariffBrlMwh,{maximumFractionDigits:2})}/MWh`}/></div><Button asChild className="mt-4"><Link to="/configuracoes">Abrir Configurações</Link></Button></SectionPanel></TabsContent>
    </Tabs>
  </InternalPage>;
}
function Goal({label,current,target,deviation}:{label:string;current:number|null;target:number|null;deviation:number|null}){return <div><div className="flex items-end justify-between gap-2"><div><div className="text-[10px] text-muted-foreground">Meta {label}</div><div className="metric-value mt-1">{formatKwTr(target)} <span className="text-[9px] text-muted-foreground">kW/TR</span></div></div><div className="text-right"><div className="text-[10px] text-muted-foreground">Atual</div><div className="metric-value mt-1">{formatKwTr(current)}</div></div></div><div className="mt-2 h-2 rounded-full bg-[linear-gradient(90deg,var(--accent-green),var(--accent-yellow),var(--accent-red))]"/><div className={`mt-1 text-[10px] font-semibold ${deviation==null?"text-muted-foreground":deviation<=0?"text-[var(--accent-green)]":"text-[var(--accent-red)]"}`}>{deviation==null?"Sem comparativo":`${Math.abs(deviation).toFixed(1).replace(".",",")}% ${deviation<=0?"abaixo":"acima"} da meta`}</div></div>}
function Mini({label,value,warn=false}:{label:string;value:string;warn?:boolean}){return <div className="rounded-lg border border-border/45 bg-muted/10 p-2.5"><div className="text-[9px] uppercase tracking-[.08em] text-muted-foreground">{label}</div><div className={`metric-value mt-1 text-sm ${warn?"text-[var(--accent-yellow)]":""}`}>{value}</div></div>}
function num(v:number|null|undefined,d=1){return v==null?"—":formatNumber(v,{maximumFractionDigits:d})}
function pct(v:number|null){return v==null?"—":`${v>0?"+":""}${formatNumber(v,{maximumFractionDigits:1})}%`}
function labelEquipment(key:string){return key.replace(/^chiller_/,"CH-").replaceAll("_"," ").toUpperCase()}
