import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript/lib/typescript.js');
const root=process.cwd(); const src=path.join(root,'src');
const files=[]; function walk(d){for(const n of fs.readdirSync(d)){const p=path.join(d,n);const st=fs.statSync(p);if(st.isDirectory())walk(p);else if(/\.(ts|tsx)$/.test(n))files.push(p)}} walk(src);
const errors=[];
for(const file of files){const text=fs.readFileSync(file,'utf8');const out=ts.transpileModule(text,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext},reportDiagnostics:true,fileName:file});for(const d of out.diagnostics||[]){if(d.category===ts.DiagnosticCategory.Error)errors.push(`${path.relative(root,file)}: ${ts.flattenDiagnosticMessageText(d.messageText,' ')}`)}}
function assert(cond,msg){if(!cond)errors.push(msg)}
const styles=fs.readFileSync(path.join(src,'styles.css'),'utf8');
assert(styles.includes('grid-template-columns: repeat(5, minmax(0, 1fr)) !important'),'Visão Geral: grid de 5 KPIs homologado ausente');
assert(styles.includes('grid-template-columns: minmax(0, 5fr) minmax(0, 3fr) minmax(0, 2fr) minmax(0, 2fr) !important'),'Visão Geral: faixa inferior 5/3/2/2 ausente');
assert(styles.includes('.ranking-workspace-body'),'Ranking: workspace lateral ausente');
assert(styles.includes('.analysis-workspace-body'),'Análises: workspace lateral ausente');
assert(styles.includes('.alerts-workspace-body'),'Alertas: workspace lateral ausente');
assert(styles.includes('.energy-workspace-body'),'Energia: workspace lateral ausente');
assert(styles.includes('.reports-workspace-body'),'Relatórios: workspace lateral ausente');
assert(styles.includes('grid-template-columns:170px minmax(0,1fr)'),'Configurações: navegação lateral homologada ausente');
const allSrc=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
assert(!/\bMWh\b/.test(allSrc),'Unidade MWh encontrada no frontend');
assert(!/\bMW\b/.test(allSrc),'Unidade MW encontrada no frontend');
assert(!allSrc.includes('Todos os Shoppings'),'Opção Todos os Shoppings não deve existir');
assert(allSrc.includes('detail-behavior-grid'),'Detalhe: composição gráfico + equipamentos ausente');
assert(allSrc.includes('analysis-workspace-body'),'Análises: composição principal ausente');
assert(allSrc.includes('alerts-workspace-body'),'Alertas: composição fila + filtros ausente');
assert(allSrc.includes('energy-workspace-body'),'Energia: composição gráfico + resumo ausente');
assert(allSrc.includes('reports-workspace-body'),'Relatórios: composição biblioteca + prévia ausente');
const fmt=fs.readFileSync(path.join(src,'utils','format.ts'),'utf8');
assert(/minimumFractionDigits\s*:\s*2/.test(fmt)&&/maximumFractionDigits\s*:\s*2/.test(fmt),'formatKwTr deve exibir exatamente 2 casas');
for(const route of ['index.tsx','shoppings.tsx','shoppings.$shoppingId.tsx','ranking.tsx','analises.tsx','alertas.tsx','esg.tsx','relatorios.tsx','configuracoes.tsx']) assert(fs.existsSync(path.join(src,'routes',route)),`Rota ausente: ${route}`);
console.log(`TS/TSX analisados: ${files.length}`); console.log(`Erros: ${errors.length}`); if(errors.length){console.error(errors.join('\n'));process.exit(1)} console.log('VALIDAÇÃO DE FONTE: PASS');
